# Generated by Django 2.0 on 2018-01-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0009_auto_20180121_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('carpet logs', models.CharField(blank=True, default='', max_length=1600, null=True)),
                ('carpet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Carpet')),
            ],
        ),
    ]
