# Generated by Django 2.0 on 2018-01-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_record_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='carpet logs',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
    ]
