# Generated by Django 2.0 on 2018-01-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20180123_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='carpet logs',
            field=models.CharField(blank=True, default='', max_length=1600),
        ),
    ]
