# Generated by Django 2.0 on 2018-01-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20180124_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='carpet logs',
            new_name='carpet log',
        ),
    ]
