# Generated by Django 2.0 on 2018-01-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20180124_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='carpet log',
        ),
    ]
