# Generated by Django 2.0 on 2018-01-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_record_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
