# Generated by Django 2.0 on 2018-01-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, default=0, null=True, verbose_name='height')),
                ('width', models.FloatField(blank=True, default=0, null=True, verbose_name='width')),
                ('neutralization', models.BooleanField(default=False, verbose_name='neutralization')),
                ('ozon', models.BooleanField(default=False, verbose_name='ozon')),
                ('impregnation', models.BooleanField(default=False, verbose_name='impregnation')),
                ('roztocz', models.BooleanField(default=False, verbose_name='roztocz')),
                ('siersc', models.BooleanField(default=False, verbose_name='siersc')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16, verbose_name='client name')),
                ('identificator', models.CharField(default='', max_length=2, verbose_name='identificator')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.SmallIntegerField(default=0, verbose_name='percent')),
                ('description', models.CharField(default='', max_length=32, null=True, verbose_name='description')),
            ],
            options={
                'ordering': ['-percent'],
            },
        ),
        migrations.CreateModel(
            name='StatusForCarpet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=16, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='StatusForTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=16, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.CharField(default='', max_length=8, verbose_name='identificator')),
                ('ticket_number', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='ticket number')),
                ('month', models.CharField(choices=[('1', 'Styczeń'), ('2', 'Luty'), ('3', 'Marzec'), ('4', 'Kwiecień'), ('5', 'Maj'), ('6', 'Czerwiec'), ('7', 'Lipiec'), ('8', 'Sierpień'), ('9', 'Wrzesień'), ('10', 'Parzdziernik'), ('11', 'Listopad'), ('12', 'Grudzień')], default='0', max_length=2, verbose_name='month')),
                ('phone_number', models.CharField(default='', max_length=12, verbose_name='client phone number')),
                ('carpets_nmb', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='carpets number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created in')),
                ('coast', models.FloatField(blank=True, default=0, null=True, verbose_name='ticket coast')),
                ('is_express', models.BooleanField(default=False, verbose_name='is express')),
                ('attentions', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='attentions')),
                ('carpets_ready_nmb', models.SmallIntegerField(blank=True, default=0, verbose_name='carpets_ready_nmb')),
                ('tags', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='tags')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.Client', verbose_name='client')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.StatusForTicket', verbose_name='status')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worker_registration.Worker', verbose_name='created_by')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='carpet',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.StatusForCarpet', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
    ]
