# Generated by Django 2.0 on 2018-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusforcarpet',
            name='short_title',
            field=models.CharField(default='', max_length=2, verbose_name='short title'),
        ),
        migrations.AddField(
            model_name='statusforticket',
            name='short_title',
            field=models.CharField(default='', max_length=2, verbose_name='short title'),
        ),
    ]
