# Generated by Django 2.0 on 2018-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20180104_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='is ready'),
        ),
    ]
