# Generated by Django 2.0 on 2018-01-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='coast',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='carpet coast'),
        ),
    ]
