# Generated by Django 2.0 on 2018-01-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_carpet_coast'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='address'),
        ),
    ]
