# Generated by Django 2.0 on 2018-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neutralization', models.SmallIntegerField(verbose_name='neutralization')),
                ('ozon', models.SmallIntegerField(verbose_name='ozon')),
                ('impregnation', models.SmallIntegerField(verbose_name='impregnation')),
                ('siersc', models.SmallIntegerField(verbose_name='siersc')),
                ('roztocz', models.SmallIntegerField(verbose_name='roztocz')),
            ],
        ),
    ]
