# Generated by Django 2.0 on 2018-02-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20180121_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='carpets_nmb',
            field=models.SmallIntegerField(default=0, verbose_name='carpets number'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='', max_length=8, verbose_name='ticket number'),
        ),
    ]
